# Generated by Django 4.1.4 on 2022-12-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Friends",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("friend1", models.IntegerField(blank=True)),
                ("friend2", models.IntegerField(blank=True)),
            ],
            options={"unique_together": {("friend1", "friend2")},},
        ),
    ]
